language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
install:
- pip install python-coveralls tox tox-travis
script: tox --recreate
after_success:
- pip install -e .
- py.test --cov=retry_decorator --cov-report=term-missing tests
- coveralls
deploy:
  provider: pypi
  user: png
  password:
    secure: "m6n470zn8+lLDoB0W/goO3ovoMScb7sVWRQcXtm7V99YtxgBzqDT+xy4nPfEeRj/0FHSL2/k9xJHV4Q8l+UfjGFR6fszXPKkSgeL4KfE0r5GuVDNIRu853f5Pa7DM8l4GNn6/NP9Lv+jVD79j8Edb4nJgTWvxOnj9PvDZJnxqjk="
  on:
    python: 2.7
